# Generated by Django 5.1.3 on 2024-11-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Image',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='is_hatchback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='is_sedan',
            field=models.BooleanField(default=False),
        ),
    ]
